Repository julie-forman-kay-lab/SPyCi-PDB, pull requests merged in 2022-09, with the labels that each got.

#21 Update tests and upload documentation for JOSS
  .github/workflows/ci.yml
  .github/workflows/draft-pdf.yml
  CHANGELOG.rst
  MANIFEST.in
  docs/installation.rst
  example/README.rst
  joss/paper.bib
  joss/paper.md
  setup.py
  tests/test_cli.py
Labels: documentation

#22 Updates to JOSS manuscript and minor bug fixes
  CHANGELOG.rst
  joss/paper.bib
  joss/paper.md
  src/spycipdb/clis/cli_cs.py
  src/spycipdb/clis/cli_rdc.py
  src/spycipdb/components/calculators.py
Labels: bug, documentation

#23 Draft 3 of JOSS Paper Edits
  CHANGELOG.rst
  README.rst
  joss/fig1.png
  joss/paper.bib
  joss/paper.md
Labels: documentation

#24 Tests and logic corrections
  .github/workflows/ci.yml
  .vscode/settings.json
  CHANGELOG.rst
  docs/installation.rst
  requirements.txt
  src/spycipdb/__init__.py
  src/spycipdb/clis/cli_cs.py
  src/spycipdb/clis/cli_jc.py
  src/spycipdb/clis/cli_noe.py
  src/spycipdb/clis/cli_pre.py
  src/spycipdb/clis/cli_rdc.py
  src/spycipdb/clis/cli_rh.py
  src/spycipdb/clis/cli_saxs.py
  src/spycipdb/clis/cli_smfret.py
  src/spycipdb/components/helpers.py
  src/spycipdb/core/calculators.py
  src/spycipdb/core/parsers.py
  src/spycipdb/libs/__init__.py
  src/spycipdb/libs/libcli.py
  src/spycipdb/libs/libparse.py
  tests/__init__.py
  tests/data/asyn_FRET.txt
  tests/data/asyn_conf.pdb
  tests/data/asyn_conf.tar.xz
  tests/data/asyn_fret_out.json
  tests/data/drksh3_JC.txt
  tests/data/drksh3_NOE.txt
  tests/data/drksh3_PRE.txt
  tests/data/drksh3_conf.pdb
  tests/data/drksh3_conf.tar.xz
  tests/data/drksh3_jc_out.json
  tests/data/drksh3_noe_out.json
  tests/data/drksh3_pre_out.json
  tests/test_calculators.py
  tests/test_clis.py
  tests/test_exceptions.py
  tests/test_libcli.py
  tests/test_libfuncs.py
  tests/test_logger.py
  tests/test_parsers.py
Labels: help wanted

#25 Polish JOSS and README
  CHANGELOG.rst
  README.rst
  docs/spycipdb_ascii1.png
  docs/spycipdb_ascii2.png
  joss/paper.md
Labels: documentation

#26 Add buttons on README.rst
  CHANGELOG.rst
  README.rst
Labels: documentation

#28 Fix `smfret` output formatting
  CHANGELOG.rst
  src/spycipdb/core/calculators.py
  tests/data/asyn_fret_out.json
Labels: bug

#29 minor corrections to the paper
  CHANGELOG.rst
  joss/paper.md
Labels: documentation
